### ISSUE TITLE
InfoController

### ISSUE THREAD

**Issue by teruto725** [ani-hovhannisyan/kanji-visualization#38]

**Comment by ani-hovhannisyan** [comment]
Implement an InfoController class which receives the data from GraphController or directly from JamDict and reformats it (if necessary). API can be:
- [ ] Get Kanji onyomi/kunyomi list together
- [ ] Get English translation
-  Get Words list with translations (OPTIONAL)
-  Get kanji writing order (OPTIONAL)

**Comment by ani-hovhannisyan** [comment]
@TakumiHiraide san please use the #3  issue for referring the usage of JamDict.

**Comment by TakumiHiraide** [comment]
I report about the error.
I installed requirements.txt that includes jamdict by "pip install -r ./backend/requirements.txt".
However, backend/Infocontroller.py doesn't work. The error is below.
File "/Users/takumi-hi/kanji-visualization/kanji-visualization/backend/InfoController.py", line 3, in 
from jamdict import Jamdict
ModuleNotFoundError: No module named 'jamdict'
The code InfoController.py is below.
#pip install jamdict jamdict-data
from jamdict import Jamdict
class InfoController:
    #from jamdict import Jamdict
    def get_jamdict_data():
        jam = Jamdict()
        print("query: ", end="")
        query = input()
        result = jam.lookup(query)
        index = -1
        print(result)
get_jamdict_data()

**Comment by TakumiHiraide** [comment]
main.py also doesn't work😭.
Traceback (most recent call last):
  File "/Users/takumi-hi/kanji-visualization/kanji-visualization/backend/main.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'

**Comment by TakumiHiraide** [comment]
Maybe I don't understand the basic import structure of python.

**Comment by TakumiHiraide** [comment]
No, main.py still cannot work, sorry.

**Comment by TakumiHiraide** [comment]
This code works because no error message appears. Does this confirm that the Fast API is working?
![スクリーンショット 2022-02-10 12 34 06](https://user-images.githubusercontent.com/84693250/153332629-d1305a56-0048-4555-bece-f36ba36ba293.png)

**Comment by ani-hovhannisyan** [comment]
Closing as it works fine on both of sides.
